educ_action_ades_homepage:
    pattern: /
    defaults: { _controller: EducActionAdesBundle:Home:index }
educ_action_ades_install:
    pattern: /install 
    defaults: { _controller: EducActionAdesBundle:Install:index }

educ_action_ades_install_db:
    pattern: /install/db
    defaults: { _controller: EducActionAdesBundle:Install:configureDb }
    methods: [GET]

educ_action_ades_install_db_submit:
    pattern: /install/db
    defaults: { _controller: EducActionAdesBundle:Install:submitDbConfig }
    methods: [POST]

educ_action_ades_install_tables:
    pattern: /install/create-tables
    defaults: { _controller: EducActionAdesBundle:Install:createTables }

educ_action_ades_install_school:
    pattern: /install/school
    defaults: { _controller: EducActionAdesBundle:Install:configureSchool }
    methods: [GET]

educ_action_ades_install_school_submit:
    pattern: /install/school
    defaults: { _controller: EducActionAdesBundle:Install:submitSchoolConfig }
    methods: [POST]

educ_action_ades_backup:
    pattern: /backup
    defaults: { _controller: EducActionAdesBundle:Backup:index}
    methods: [GET]

educ_action_ades_backup_old:
    pattern: /sauver.php
    defaults: { _controller: EducActionAdesBundle:Backup:index}
    methods: [GET]

educ_action_ades_backup_create:
    pattern: /backup/create
    defaults: { _controller: EducActionAdesBundle:Backup:backup}
    methods: [POST]

educ_action_ades_backup_upload:
    pattern: /backup/upload
    defaults: { _controller: EducActionAdesBundle:Backup:upload}
    methods: [POST]

educ_action_ades_backup_delete:
    pattern: /backup/delete/{file}
    defaults: { _controller: EducActionAdesBundle:Backup:delete}
    methods: [GET]

educ_action_ades_backup_restore:
    pattern: /backup/restore/{file}
    defaults: { _controller: EducActionAdesBundle:Backup:restore}
    methods: [GET]

educ_action_ades_backup_download:
    pattern: /backup/download/{file}
    defaults: { _controller: EducActionAdesBundle:Backup:download}
    methods: [GET]

educ_action_ades_logout:
    pattern: /logout
    defaults: { _controller: EducActionAdesBundle:Logout:index }
    methods: [GET]
