educ_action_ades_homepage:
    pattern: /
    defaults: { _controller: EducActionAdesBundle:Home:index }
educ_action_ades_install:
    pattern: /install 
    defaults: { _controller: EducActionAdesBundle:Install:index }

educ_action_ades_install_db:
    pattern: /install/db
    defaults: { _controller: EducActionAdesBundle:Install:configureDb }
    methods: [GET]

educ_action_ades_install_db_submit:
    pattern: /install/db
    defaults: { _controller: EducActionAdesBundle:Install:submitDbConfig }
    methods: [POST]

educ_action_ades_install_tables:
    pattern: /install/create-tables
    defaults: { _controller: EducActionAdesBundle:Install:createTables }

educ_action_ades_install_school:
    pattern: /install/school
    defaults: { _controller: EducActionAdesBundle:Install:configureSchool }
    methods: [GET]

educ_action_ades_install_school_submit:
    pattern: /install/school
    defaults: { _controller: EducActionAdesBundle:Install:submitSchoolConfig }
    methods: [POST]

educ_action_ades_backup:
    pattern: /backup
    defaults: { _controller: EducActionAdesBundle:Backup:index}
    methods: [GET]

educ_action_ades_backup_delete_many:
    pattern: /backup
    defaults: { _controller: EducActionAdesBundle:Backup:deleteMany}
    methods: [POST]

educ_action_ades_backup_old:
    pattern: /sauver.php
    defaults: { _controller: EducActionAdesBundle:Backup:index}
    methods: [GET]

educ_action_ades_backup_create:
    pattern: /backup/create
    defaults: { _controller: EducActionAdesBundle:Backup:backup}
    methods: [POST]

educ_action_ades_backup_upload:
    pattern: /backup/upload
    defaults: { _controller: EducActionAdesBundle:Backup:upload}
    methods: [POST]

educ_action_ades_backup_delete:
    pattern: /backup/delete/{file}
    defaults: { _controller: EducActionAdesBundle:Backup:delete}
    methods: [GET]

educ_action_ades_backup_restore:
    pattern: /backup/restore/{file}
    defaults: { _controller: EducActionAdesBundle:Backup:restore}
    methods: [GET]

educ_action_ades_backup_download:
    pattern: /backup/download/{file}
    defaults: { _controller: EducActionAdesBundle:Backup:download}
    methods: [GET]

educ_action_ades_logout:
    pattern: /logout
    defaults: { _controller: EducActionAdesBundle:Logout:index }
    methods: [GET]

educ_action_ades_logout_old:
    pattern: /deconnexion.php
    defaults: { _controller: EducActionAdesBundle:Logout:index }
    methods: [GET]

educ_action_ades_logout_clear:
    pattern: /logout
    defaults: { _controller: EducActionAdesBundle:Logout:clearLogout }
    methods: [POST]

educ_action_ades_login:
    pattern: /accueil.php

educ_action_ades_import_proeco:
    pattern: /import-proeco
    defaults: { _controller: EducActionAdesBundle:Import:index }
    methods: [GET]

educ_action_ades_import_proeco_old:
    pattern: /importer.php
    defaults: { _controller: EducActionAdesBundle:Import:index}
    methods: [GET]

educ_action_ades_import_proeco_upload:
    pattern: /import-proeco
    defaults: { _controller: EducActionAdesBundle:Import:upload }
    methods: [POST]

educ_action_ades_import_proeco_preview:
    pattern: /import-proeco/preview
    defaults: { _controller: EducActionAdesBundle:Import:preview }
    methods: [GET]

educ_action_ades_import_confirm:
    pattern: /import-proeco/confirm
    defaults: { _controller: EducActionAdesBundle:Import:confirm }
    methods: [POST]

educ_action_ades_import_proeco_done:
    pattern: /import-proeco/done
    defaults: { _controller: EducActionAdesBundle:Import:done }
    methods: [GET]

educ_action_ades_upgrade:
    pattern: /upgrade-db
    defaults: { _controller: EducActionAdesBundle:Upgrade:index }
    methods: [GET]

educ_action_ades_upgrade_do:
    pattern: /upgrade-db
    defaults: { _controller: EducActionAdesBundle:Upgrade:upgrade }
    methods: [POST]

educ_action_ades_upgrade_restore:
    pattern: /upgrade-db/restore/{file}
    defaults: { _controller: EducActionAdesBundle:Upgrade:restore }
    methods: [GET]

educ_action_ades_fact_create_one:
    pattern: /fact/new/{factTypeId}/student/{studentId}
    defaults: { _controller: EducActionAdesBundle:Fact:create }
    methods: [GET]

educ_action_ades_fact_post:
    pattern: /fact
    defaults: { _controller: EducActionAdesBundle:Fact:post }
    methods: [POST]

educ_action_ades_fact_done:
    pattern: /fact
    defaults: { _controller: EducActionAdesBundle:Fact:showDone }
    methods: [GET]

educ_action_ades_fact_edit:
    pattern: /fact/edit/{id}
    defaults: { _controller: EducActionAdesBundle:Fact:edit }
    methods: [GET]

educ_action_ades_detention_new_subscription:
    pattern: /detention/add/{detentionId}
    defaults: { _controller: EducActionAdesBundle:Fact:addStudentToDetention }
    methods: [GET]
