educ_action_ades_install:
    pattern: /install 
    defaults: { _controller: EducActionAdesBundle:Install:index }

educ_action_ades_install_db:
    pattern: /install/db
    defaults: { _controller: EducActionAdesBundle:Install:configureDb }
    methods: [GET]

educ_action_ades_install_db_submit:
    pattern: /install/db
    defaults: { _controller: EducActionAdesBundle:Install:submitDbConfig }
    methods: [POST]

educ_action_ades_install_tables:
    pattern: /install/create-tables
    defaults: { _controller: EducActionAdesBundle:Install:createTables }

educ_action_ades_install_school:
    pattern: /install/school
    defaults: { _controller: EducActionAdesBundle:Install:configureSchool }
    methods: [GET]

educ_action_ades_install_school_submit:
    pattern: /install/school
    defaults: { _controller: EducActionAdesBundle:Install:submitSchoolConfig }
    methods: [POST]
