services:
    educ_action.ades.twig:
        class: EducAction\AdesBundle\Twig\TwigExtension
        arguments: ["@request_stack"]
        tags:
            - { name: twig.extension }

    educ_action.ades.kernel_listener:
        class: EducAction\AdesBundle\KernelListener\KernelListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onControllerListener }
    educ_action.ades.user:
        class : EducAction\AdesBundle\UserInstance
        arguments: ["@request_stack"]
