version: "3"
services:
  web:
    build:
      context: ./docker
      dockerfile: runtime-base.dockerfile
    ports: ["3000:80"]
    volumes:
      - .:/ades
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/init.sql:/script/init.sql
      - mysql_data:/var/lib/mysql
    command: "--init-file /script/init.sql"
    ports: ["3307:3306"]
volumes:
  mysql_data:
