version: "3"
services:
  web:
    build: ./docker
    image: ades
    ports: ["3000:80"]
    volumes:
      - .:/ades
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/init.sql:/script/init.sql
    command: "--init-file /script/init.sql"
    ports: ["3309:3306"]
