imports:
    - { resource: config.yml }
    - { resource: ../../local/dev.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler:
        enabled: "%profiler.enabled%"
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false
