imports:
    - { resource: ../../local/config.yml }

framework:
    secret: '%secret%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    session:
        handler_id: ~
    templating:
        engines: ["twig"]
twig:
    strict_variables: true
